services:
  app:
    image: mcr.microsoft.com/devcontainers/java:21
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: comicflix
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"